# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'piip' do

# web service
pod 'SwiftyJSON'
pod 'ReachabilitySwift'
pod 'Starscream', '~> 1.1.3'
pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper.git'

# fabric
pod 'Fabric'
pod 'Crashlytics'
pod 'Digits'
pod 'TwitterCore'

# logger
pod 'XCGLogger', '~> 3.3'

# gcm
pod 'Google/CloudMessaging'

# ActionPicker
pod 'ActionSheetPicker-3.0'


end
